image: alpine:latest

include:
  - project: ifood/pipelines/gitlab-pipelines
    ref: ifood-backend-1-stable
    file: pipelines/ifood-backend/main.yml

stages:
  - rollback
  - pipeline info
  - compliance check
  - test
  - security publish report
  - code analysis
  - build
  - review deploy
  - stop review deploy
  - stop deploy
  - sandbox deploy
  - canary start
  - canary check
  - deploy
  - release
  - canary on branch reject
  - warmup hpa
  - redeploy
  - check hpa
  - cooldown hpa
  - conclude

finish:
  stage: conclude
  image: registry.infra.ifood-prod.com.br/ifood/platform-engineering/oss/github-check-updater:latest 
  variables: 
    REPOSITORY: batatinha-delivery/test-forks-pr
    SHA: ${CI_COMMIT_SHA}
  script:
    - cd /src
    - node check_success.js

unit-tests:
  stage: test
  image: maven:3.6.3-openjdk-17
  script:
    - mvn -Dmaven.repo.local=$BUILD_CACHE_PATH $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
      - "target"
  cache:
    paths:
      - $BUILD_CACHE_PATH